# Generated by Django 3.0.3 on 2020-02-23 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='images/game/default.png', upload_to='images/game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.GameType'),
        ),
    ]
