# Generated by Django 3.0.3 on 2020-02-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200223_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gametype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
