# Generated by Django 3.0.3 on 2020-02-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='game.GameType'),
            preserve_default=False,
        ),
    ]
