# Generated by Django 3.0.3 on 2020-03-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200226_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='images/app/game/default.png', upload_to='images/game'),
        ),
    ]
