# Generated by Django 3.0.3 on 2020-02-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200223_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
    ]
