# Generated by Django 3.0.3 on 2020-02-23 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_group'),
        ('game', '0005_remove_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Group'),
            preserve_default=False,
        ),
    ]
