# Generated by Django 3.0.3 on 2020-02-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200223_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='group',
        ),
    ]
