# Generated by Django 3.0.3 on 2020-03-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.CharField(choices=[('F0', 'Free'), ('P0', 'Paid')], default='F0', max_length=2),
        ),
    ]
