# Generated by Django 3.0.3 on 2020-02-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_game_group'),
        ('user', '0006_auto_20200223_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='game.GameType'),
            preserve_default=False,
        ),
    ]
