# Generated by Django 3.0.3 on 2020-03-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20200301_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(default='images/app/organization/default.png', upload_to='images/organization'),
        ),
    ]
